### ISSUE TITLE
Supplementary materials

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/manydepth#1]
Hi nianticlabs:

Thank you for sharing this amazing research project to the community! 
just one question, where can we access the supplementary materials for this paper?

thank you!

sincerely
Ziyue Feng

**Comment by mdfirman** [comment]
Hi! Thanks for your interest in this project.

We expect supplementary material to be uploaded to the end of the arxiv file within the next couple of weeks.

I'll leave this issue open until we've done that. 

Thanks

**Comment by JamieWatson683** [comment]
Sorry for the delay with this - it is now online appended to the arxiv version.

Thanks a lot!
