### ISSUE TITLE
Feature request: Tensorflow lite version

### ISSUE THREAD

**Issue by rodrigoGA** [nianticlabs/manydepth#10]
first congratulations on the project, and thank you for sharing this research and the models.

I am interested in a tensorflow lite version of this model, I appreciate if you can share it in case you have it. I would like to test it on a device android with very little resources.

**Comment by JamieWatson683** [comment]
Hi, thanks for your interest in the project!

Unfortunately no, we do not have a tensorflow lite version of the model available - sorry I cannot be of more help.
