### ISSUE TITLE
Stereo + Temporal

### ISSUE THREAD

**Issue by fengziyue** [nianticlabs/manydepth#12]
Hi:

Thank you for sharing this wonderful work!

In the Monodepth2 you tried the Monocular, Stereo, and M+S, have you try the stereo in this manydepth setting? does it has much performance boost over monocular?

Thank you!

**Comment by mdfirman** [comment]
Thanks for your interest!

I think we did try this, but I'm not sure we trained models like-for-like with the ones in the paper (so I wouldn't like to give any numbers or make direct comparisons). 

I seem to remember it did quite a lot better than monocular, which isn't really surprising – the extra supervision from stereo is quite considerable.

Two things to bear in mind:

* If training from stereo, most of the manydepth contributions are not needed
* Stereo will give depths in real-world units, which could be useful.

@JamieWatson683  any more thoughts?

**Comment by JamieWatson683** [comment]
Hi,

As @mdfirman says we did initially experiment with this, but felt like an interesting task was attempting to train from monocular video only. 

If you were interested, adapting the code for this probably won't be too hard, as you can copy the stereo loading parts from Monodepth2. From memory if you use M+S and Depth Hints (our other repo) you can get a reasonable improvement.

Thanks a lot!
