### ISSUE TITLE
Can you provide more ablations about mask?

### ISSUE THREAD

**Issue by whyygug** [nianticlabs/manydepth#14]
Hi，thank you for your excellent work！
The mask you proposed is very useful, but I still have some questions. 
In the body of the paper, your loss is:
![11](https://user-images.githubusercontent.com/31730585/120063858-df139b00-c09b-11eb-8da9-3963a5e8bf8c.PNG)

but have you tried to remove (1-M) for Lp ? like this:
![22](https://user-images.githubusercontent.com/31730585/120063897-14b88400-c09c-11eb-86ea-7ec397d520be.PNG)

or remove M and (1-M) both:
![33](https://user-images.githubusercontent.com/31730585/120063922-36b20680-c09c-11eb-8e32-15ae89d884a4.PNG)

And another question: in your ablation you show that the performance of Manydepth(with motion masking, w/o teacher) is much worse than the performance of Manydepth(w/o motion masking),  what's your thoughts of this phenomenon?  I think adding the motion masking to Lp will make the model better,  because the model will not attempt to reproject moving objects,  but the results seem to get much worse.

**Comment by mdfirman** [comment]
Hi, thanks for your interest!

We never ran these additional ablations, but they should be very easy to code up and run given our codebase. 

For your second question: My main thought here would be that the teacher is a very strong signal, as it really helps to fix up problems in areas of moving objects. 

On the other hand, the motion masking by itself doesn't actually fix up problems in areas of moving objects; it just doesn't apply a loss in these regions. What this means is that the network *never gets taught not to trust the cost volume*. I.e., Manydepth(with motion masking, w/o teacher) can happily get a good loss by propogating through the mistakes in the cost volume through to the final depth prediction – as it is never taught what the right answer is in the masked regions.

**Comment by whyygug** [comment]
Thanks for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nianticlabs/manydepth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nianticlabs/manydepth] Can you provide more ablations about mask? (#14)





 
Hi, thanks for your interest!
 
We never ran these additional ablations, but they should be very easy to code up and run given our codebase.
 
For your second question: My main thought here would be that the teacher is a very strong signal, as it really helps to fix up problems in areas of moving objects.
 
On the other hand, the motion masking by itself doesn't actually fix up problems in areas of moving objects; it just doesn't apply a loss in these regions. What this means is that the network never gets taught not to trust the cost volume. I.e., Manydepth(with motion masking, w/o teacher) can happily get a good loss by propogating through the mistakes in the cost volume through to the final depth prediction – as it is never taught what the right answer is in the masked regions.
