### ISSUE TITLE
Pre-trained models for monocular depth networks

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [nianticlabs/manydepth#15]
Thank you for open-sourcing this very interesting work. Would it be possible to also provide weights for the monocular depth networks (the teacher networks) that go along with the currently available pre-trained models? Thank you!

**Comment by JamieWatson683** [comment]
Hi - sorry for the delay. 

Sure, I will try to dig them out and upload.

**Comment by JamieWatson683** [comment]
Hi - just added to the zips for the KITTI models.

Let me know if you need the cityscapes one too and I can add.

Thanks a lot!

**Comment by JamieWatson683** [comment]
Additionally I've added some code to evaluate the teacher networks themselves - I hope this helps!

**Comment by VitorGuizilini-TRI** [comment]
Thank you! Do you know if these teacher networks, when trained from scratch jointly with the student multi-frame network, achieve a similar performance to when they are trained separately, as in monodepth2?

**Comment by JamieWatson683** [comment]
Yes, they generally perform to the same level as monodepth2 - I've added the ability to test these by adding thee flag `--eval_teacher` to the `evaluate_depth.py` script. Let me know if that helps!

Thanks a lot
