### ISSUE TITLE
batch size 8 got abs rel 0.130

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/manydepth#18]
Hi, thanks for your great work and sharing code.
I have a V100 GPU but I cannot start training with batch size 12. The maximum value of batch size I can use is 8. And I didn't change other parameters. Then I got a bad performance.
![image](https://user-images.githubusercontent.com/28101548/122154785-49984980-ce98-11eb-8b61-35c9fc005ac8.png)
![image](https://user-images.githubusercontent.com/28101548/122154928-8e23e500-ce98-11eb-9d88-99eb1c195d09.png)
How should I do to get a better performance?

**Comment by sunnyHelen** [comment]
Sorry to bother you again. I test your provided models "KITTI_MR" and "KITTI_HR", which also cannot achieve the performance reported in your paper. I do the evaluation following your guidance in the readme. Is there anything I should pay attention to get the correct test results?
![image](https://user-images.githubusercontent.com/28101548/122325040-70b84f00-cf5c-11eb-9a75-c654a761ccd3.png)
![image](https://user-images.githubusercontent.com/28101548/122325114-8ded1d80-cf5c-11eb-8db7-d091448e0950.png)

**Comment by mdfirman** [comment]
Hi @sunnyHelen  – thanks for reporting this, this is really interesting.

When I check out the code, download and unzip the pretrained model, I get the results we report in the paper (here showing the MR results):
```
mfirman@seine:/mnt/nas/mfirman/code/public/manydepth$ conda activate manydepth
(manydepth) mfirman@seine:/mnt/nas/mfirman/code/public/manydepth$ CUDA_VISIBLE_DEVICES=0 python -m manydepth.evaluate_depth --data_path /mnt/nas/shared/datasets/kitti/KITTI_clement/KITTI/ --load_weights_folder KITTI_MR --eval_mono
-> Loading weights from KITTI_MR
-> Computing predictions with size 192x640
min depth bin 0.12260909493485274 - max depth bin 6.020557924236172
59it [00:10,  5.68it/s]
finished predicting!
-> Evaluating
   Mono evaluation - using median scaling
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 697/697 [00:03<00:00, 191.82it/s]
 Scaling ratios | med: 34.628 | std: 0.083

   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 |
&   0.098  &   0.770  &   4.459  &   0.176  &   0.900  &   0.965  &   0.983  \\

-> Done!
```

Can we check a few things:

* Are you using the exact versions of the dependencies in the `environment.yml` file? I notice you are getting some warnings which I'm not getting e.g. around `grid_sample`.  I did it the classic way of `conda env create -f environment.yml -n manydepth` then `conda activate manydepth` to get the right results.
* Let's check the integrity of the ground truth depths file: `md5sum splits/eigen/gt_depths.npz` gives `5ee063672db21c6210ec2673a8ade2a8` for me.

**Comment by mdfirman** [comment]
(Tagging @JamieWatson683 for visibility)

**Comment by sunnyHelen** [comment]
Hi, thanks for your reply. The gt_depths.npz has no problem. But I used the environment for monodepth2 which I built before. I'll check if it's an issue with the environment and report to you.

**Comment by sunnyHelen** [comment]
Hi, I rebuilt my environment for manydepth, and the result is correct. In the new environment, batchsize 12 is ok. It seems environment setting matters a lot. Thanks for your help.
