### ISSUE TITLE
how to do the ablation study without teacher

### ISSUE THREAD

**Issue by sunnyHelen** [nianticlabs/manydepth#21]
Hi, I want to try to do your ablation study without the teacher network.
It is "ManyDepth (with motion masking, w/o teacher) 0.154" in table 4 in your paper.
I mention there are choices about freezing the teacher network. How to get the results of models without the teacher.

**Comment by JamieWatson683** [comment]
Hi - thanks for your interest in the paper!

In this ablation, we still mask out the reprojection loss but do not apply a consistency loss. Perhaps the easiest way to recreate this would be to add `and False` to line 612, which means the consistency loss is always set to 0.

https://github.com/nianticlabs/manydepth/blob/28fbbcfa4370eb9c28860b8ab72b09547c0d14d0/manydepth/trainer.py#L612

Let me know how you get on with this.

Thanks a lot!
