### ISSUE TITLE
How to debug when training with "python -m manydepth.train"

### ISSUE THREAD

**Issue by ruili3** [nianticlabs/manydepth#24]
Thanks for the impressive work! I have a question for the tools you use for debugging manydpeth. As you use "python -m manydepth.train" to specify the level of path, I can't find a way to debug using VsCode because no runnable .py file can be used to start running the code. So can you give some insights to debug the code? 
Thanks a lot!

**Comment by JamieWatson683** [comment]
Hi, and thanks for your interest in the repo!

I'm not too familiar with debugging with VsCode, but if you use PyCharm you can set the debugger to use a configuration with a module name, rather than a script name. 

Let me know if this works for you.

Thanks a lot
