### ISSUE TITLE
Freeze Teacher network from beginning

### ISSUE THREAD

**Issue by pjckoch** [nianticlabs/manydepth#25]
Hi, 

thanks a lot for sharing this.

I have a fully pre-trained teacher network and tried to freeze its weights directly from the beginning, as I guess it does not make sense to train it further.

However, if I set `--freeze_teacher_and_pose` as a run option, then `self.min_depth_tracker` and `self.max_depth_tracker` are never set in trainer.py, because following lines are **not** called:

https://github.com/nianticlabs/manydepth/blob/7e4c46fb0565179801116e8cd051e18371d29aed/manydepth/trainer.py#L59-L60

Thus, I get an error on the following lines:

https://github.com/nianticlabs/manydepth/blob/7e4c46fb0565179801116e8cd051e18371d29aed/manydepth/trainer.py#L306-L307

How do you suggest to initialize `self.min_depth_tracker` and `self.max_depth_tracker` in case of freezing teacher weights from the beginning on? I suppose it makes sense to initialize it to reflect the range of depth values that my pretrained model produces?

Thanks in advance and best regards,
Patrick

**Comment by JamieWatson683** [comment]
Hi Patrick,

Thanks a lot for your interest in the repo!

Ah yes good catch - yes I think those lines should live outside the `if` such that they are set regardless. You can then set these to be in a sensible range given some depth predictions on the training set.

**Comment by pjckoch** [comment]
Hi!

Thank you for getting back to me. Ok, great, that makes sense.

Thanks again and best regards,
Patrick
