### ISSUE TITLE
Question About Input Image Size

### ISSUE THREAD

**Issue by benhgm** [nianticlabs/manydepth#42]
Hi there, I am trying to train the model using KITTI Raw dataset images. I realize that the KITTI raw images have a resolution of 1242 x 375 while the default image settings for the model is 640 x 192. Do I have to resize all the KITTI raw images to 640 x 192 before using them for training? Thank you for your advice!

**Comment by JamieWatson683** [comment]
Hi - we just resize them on the fly during training to either `640x192` or `1024x320` inside the dataloader.
