### ISSUE TITLE
how to choose the best  freeze_teacher_epoch parameter?

### ISSUE THREAD

**Issue by dkerjw1** [nianticlabs/manydepth#43]
Hi,  thanks for sharing the great work!

But I'm confused that when I trained with custom dataset,  how to choose the best  freeze_teacher_epoch parameter?  Does this have anything to do with the amount of data?

Looking forward to your reply. Thank you!

**Comment by qingyuemeng** [comment]
I trained on some few images from KITTI,  and I tried to set ```--freeze_teacher_epoch 15``` like trainning on  the full KITTI dataset,  but I got the results like this:
![iTerm2 x1CpID 0000000001](https://user-images.githubusercontent.com/33691506/142404048-6c5f24f2-be30-4b93-95a2-6b00c59de3db.png)

![iTerm2 84neJN 0000000001_disp_multi](https://user-images.githubusercontent.com/33691506/142404025-4d0b904b-e93a-43f6-b2e7-2c38d5fd6802.jpeg)

Is there something wrong?
