### ISSUE TITLE
Bug in intrinsics re-scaling?

### ISSUE THREAD

**Issue by aj96** [nianticlabs/manydepth#49]
I noticed you are updating intrinsics like so:

K[0, :] *= self.width // (2 ** scale)
K[1, :] *= self.height // (2 ** scale)

Aren't you supposed to multiply the intrinsics by the ratio of the new_shape / orig_shape? If you are resizing your img to be self.width // (2 ** scale), then shouldn't it be K[0, :] *= (self.width // (2 ** scale * orig_width)) where orig_width is the original width of the image before resizing?

What you are doing here seems to be just multiplying the intrinsics by the size of the new image. That cannot be. Am I mis-reading the code?

**Comment by brandleyzhou** [comment]
I think you are right. but please note that every element in K is normalized. namely, here k[0, :] = original_K[0, :] / original_width, so when we change the image size, we just need to multiply the new size.

**Comment by daniyar-niantic** [comment]
The K is normalized, so multiplying it with the size of the new image will give correct result.
