### ISSUE TITLE
Contact person / email

### ISSUE THREAD

**Issue by Yevkuzn** [nianticlabs/manydepth#5]
Hi,
thanks for the interesting paper. 
I found a small issue in the content of the paper and would like to discuss it with the main contact, but couldn't find any contact details in the paper.

Looking forward to hearing from you
Yevhen

**Comment by mdfirman** [comment]
Hi Yevkuzn,

Thanks a lot for your interest. Please feel free to email me. My email address starts with mfirman and then has an @ sign and ends with nianticlabs.com. 

I'll look into it for you.

Thanks,

Michael

**Comment by Yevkuzn** [comment]
thx for responding promptly
