### ISSUE TITLE
Depth evaluation for single frame mode?

### ISSUE THREAD

**Issue by LeeBY68** [nianticlabs/manydepth#51]
Thanks for the wonderful work! 

I have a question for the depth evaluation:
When I evaluate the depth performance of a single image, which has no previous frame, I set
` "--zero_cost_vulome" and "--num_matching_frames = 0" `
for the evaluation options.
However, the "evaluate_depth" encouter a failure: because "frames_to_load[1:]" is empty, the "lookup_frames" receive the empty Tensor-list. 

What should I set or change for the single frame mode evaluation, where the test frame has completely no previous frames or future frames?

**Comment by daniyar-niantic** [comment]
Hi. You should use `test_simple.py`. You can specify the target image for `source_image_path` (as well as `target_image_path`) but use `mode='mono'` so that the source image is ignored during prediction.

**Comment by zshn25** [comment]
Does the `—static_camera` flag simulate single frame inference during evaluation? I would like to run the evaluate_depth.py but with single frame as input
