### ISSUE TITLE
The results of cityscapes

### ISSUE THREAD

**Issue by Ecalpal** [nianticlabs/manydepth#52]
Hi, @JamieWatson683 @daniyar-niantic 

I evaluate the model with [CityScapes (512x192)](https://storage.googleapis.com/niantic-lon-static/research/manydepth/models/CityScapes_MR.zip) and got the same number as that in Table 3 in your [paper (IEEE)](https://ieeexplore.ieee.org/document/9577529) and [paper (arxiv)](https://arxiv.org/pdf/2104.14540.pdf).

Is the resolution in Table 3 a clerical error? (416x128 in the paper, 512x192 in the weights)
Is there a revised version of the paper available for reference?

**Comment by daniyar-niantic** [comment]
@Ecalpal Hi. Thanks for asking. I think @JamieWatson683 is the best person to answer your question.

In the meantime, may I ask why you closed the issue?

**Comment by Ecalpal** [comment]
> @Ecalpal Hi. Thanks for asking. I think @JamieWatson683 is the best person to answer your question.
> 
> In the meantime, may I ask why you closed the issue?

Hi, @daniyar-niantic, thanks for your reply. 

I closed this issue because I have found the answer [here](https://github.com/nianticlabs/manydepth/issues/35#issuecomment-902470888).

**Comment by daniyar-niantic** [comment]
Ah, thanks for the link! I guess this is truly closed then.
