### ISSUE TITLE
Why the training time of manydepth is much shorter than monodepth2?

### ISSUE THREAD

**Issue by myalos** [nianticlabs/manydepth#65]
I use the same training environment (python 3.7, 3080ti) to train manydepth and monodepth2 separately. Since we train a complete monodepth2 as a teacher in manydepth, the training time of manydepth is longer than mondepth2. But the fact is the training time of manydepth is about 7.5h  and monodepth2 is about 14h in scale 0 1 quite counter-intuitive.  Could anybody tell me why this could happen?
In training console output of manydepth:
epoch   1 | batch    683 | examples/s:  33.7 | loss: 0.29235 | time elapsed: 00h26m29s | time left: 06h52m52s
Thanks in advance!

**Comment by JamieWatson683** [comment]
Hi - sorry for the delay.

Interesting observation! I am not sure - are both the same batch size, number of epochs, resolution etc?

If it's nothing obvious like the above, then let me know and I can have a think.

Thanks a lot!

**Comment by myalos** [comment]
thanks for reply and sorry for late
I tried both at same batch size 12 , same epochs 20 and same resolution(default 640x192)
I have tried to add cudnn.determinisitc = True, delete log and val function in run_epoch function, try only scale 0 training, transform code structure to manydepth python -m, and add os.[''...''] to monodepth2, but manydepth is still much faster.
I found that manydepth's power usage is around 320W with low std, and monodepth2's power usage is 150W around->240W around->300W around -> 150W around ->...  by using watch -n 1 nividia-smi command
I am curious and I can't understand why that happened

**Comment by myalos** [comment]
I find the answer, because in manydepth
if self.load_depth and False:
and in monodepth2:
if self.load_depth
