### ISSUE TITLE
About MAX gt_depth

### ISSUE THREAD

**Issue by wangjiyuan9** [nianticlabs/manydepth#67]
Hello！Dear Author ,thank you for your contribution!
In the code, I found that you set MAX depth as 80 in both Kitti and Cityscape. Actually, I wonder:
1.The unit of the num in the ".npy" file. Are they in meter?
2. Why always use 80m as the MAX depth? I checked the MAX value of your cityscape gt_depth is 473.5748014025198
And the MAX value of Kitti dataset gt_depth is about 82. So I think the "80" is ok for Kitti but not adapted to Cityscape.

**Comment by JamieWatson683** [comment]
Hi - thanks for the question!

We used a max depth of 80m to be consistent and comparable with prior works (e.g. struct2depth). 

But yes, I agree that a cap of 80m might be too small for cityscapes - although bear in mind that the GT depth for cityscapes is recovered from stereo matching (SGM), and so the GT values are likely to be unreliable for far away objects.

**Comment by wangjiyuan9** [comment]
Thanks！！！
