### ISSUE TITLE
Calculate the gt depth for Cityscape images

### ISSUE THREAD

**Issue by wangjiyuan9** [nianticlabs/manydepth#69]
Dear:
First of all, thank you for your amazing paper ！
I encountered a problem when I read your public code：
I‘d like to calculate the gt_depth of the image for the training part (not all). Do you still have the Calculation code ?
Thank you for your time and help!

**Comment by wangjiyuan9** [comment]
hello?

**Comment by wangjiyuan9** [comment]
hi？

**Comment by JamieWatson683** [comment]
Hi sorry for the delay - Cityscapes provide intrinsics, camera baseline and disparity map, so to recover the depth map you simply do:
`depth = focal length [in pixels] x baseline [in metres] / disparity`
