### ISSUE TITLE
The dataset GT-Calculation

### ISSUE THREAD

**Issue by wangjiyuan9** [nianticlabs/manydepth#71]
Dear:
First of all, thank you for your amazing paper ！
I encountered a problem when I read your public code：
I‘d like to calculate the gt_depth of the image for the training part (not all). Do you still have the Calculation code ?
Thank you for your time and help!

**Comment by JamieWatson683** [comment]
Hi sorry for the delay - Cityscapes provide intrinsics, camera baseline and disparity map, so to recover the depth map you simply do:
`depth = focal length [in pixels] x baseline [in metres] / disparity`

**Comment by GuanghuiWei** [comment]
<img width="998" height="915" alt="Image" src="https://github.com/user-attachments/assets/240fb663-a638-4d1d-991a-7b25e0c841e5" />

Thank you very much for your response. I've converted from disp to depth using the formula you provided. Here is my conversion code. If you could kindly review it for any errors, I would be most grateful.
