### ISSUE TITLE
Train on own dataset with not good result

### ISSUE THREAD

**Issue by xuzhiyuan29** [nianticlabs/manydepth#8]
Hi, thanks for your interesting paper and innovative ideas on depth estimation. I am trying to use your model to train on our own campus dataset to see if it works well in real time.  As a  freshman on deep learning, I follow your experiment implementation and code instructions but still get frustrating results. Could you give me some advice on training to get a better result?
------------------------------------------------------------
My frame order is [0,-1,1], so I changed the code to match the input.
![Screenshot from 2021-05-12 21-53-15](https://user-images.githubusercontent.com/38434962/117986797-84283700-b36c-11eb-8620-d040348bca1b.png)
------------------------------------------------------------
My result:
![Screenshot from 2021-05-12 21-57-27](https://user-images.githubusercontent.com/38434962/117987681-4c6dbf00-b36d-11eb-81f5-b1d955a30c9d.png)
![Screenshot from 2021-05-12 21-57-31](https://user-images.githubusercontent.com/38434962/117987684-4d9eec00-b36d-11eb-8131-241e6b0118a3.png)
![Screenshot from 2021-05-12 21-57-40](https://user-images.githubusercontent.com/38434962/117987691-4ed01900-b36d-11eb-87af-38b4d0f156da.png)
![Screenshot from 2021-05-12 21-57-50](https://user-images.githubusercontent.com/38434962/117987694-4f68af80-b36d-11eb-8478-7d9865dd61f8.png)
![Screenshot from 2021-05-12 21-58-09](https://user-images.githubusercontent.com/38434962/117987698-50014600-b36d-11eb-9f00-ba6c12dd43f9.png)
![Screenshot from 2021-05-12 21-58-17](https://user-images.githubusercontent.com/38434962/117987711-5263a000-b36d-11eb-8116-25914fa26207.png)
![Screenshot from 2021-05-12 21-58-25](https://user-images.githubusercontent.com/38434962/117987715-52fc3680-b36d-11eb-9dfa-3148dffaef72.png)
![Screenshot from 2021-05-12 21-58-30](https://user-images.githubusercontent.com/38434962/117987719-5394cd00-b36d-11eb-8fcb-8528e1071d64.png)
![Screenshot from 2021-05-12 21-58-34](https://user-images.githubusercontent.com/38434962/117987723-54c5fa00-b36d-11eb-9fee-3d69ead1e2f9.png)
![Screenshot from 2021-05-12 21-58-38](https://user-images.githubusercontent.com/38434962/117987725-55f72700-b36d-11eb-8054-6d07ad7beaf9.png)
![Screenshot from 2021-05-12 21-58-42](https://user-images.githubusercontent.com/38434962/117987729-57285400-b36d-11eb-944f-8a0188ad7feb.png)
------------------------------------------------------------
My settings:
{
  "data_path": "/media/xzy/daa84e38-7f66-4aa4-a0ce-4fe978abe706/xzy/Downloads/manydepth/dump_root",
  "log_dir": "/media/xzy/daa84e38-7f66-4aa4-a0ce-4fe978abe706/xzy/Downloads/manydepth/log",
  "model_name": "Vecan_model",
  "split": "vecan",
  "num_layers": 18,
  "depth_binning": "linear",
  "num_depth_bins": 96,
  "dataset": "cityscapes_preprocessed",
  "png": true,
  "height": 192,
  "width": 640,
  "disparity_smoothness": 0.001,
  "scales": [
    0,
    1,
    2,
    3
  ],
  "min_depth": 0.1,
  "max_depth": 80.0,
  "frame_ids": [
    0,
    -1,
    1
  ],
  "batch_size": 8,
  "learning_rate": 0.0001,
  "num_epochs": 20,
  "scheduler_step_size": 15,
  "freeze_teacher_and_pose": false,
  "freeze_teacher_epoch": 5,
  "v1_multiscale": false,
  "avg_reprojection": false,
  "disable_automasking": false,
  "no_ssim": false,
  "weights_init": "pretrained",
  "use_future_frame": false,
  "num_matching_frames": 1,
  "disable_motion_masking": false,
  "no_matching_augmentation": false,
  "no_cuda": false,
  "num_workers": 8,
  "load_weights_folder": "/media/xzy/daa84e38-7f66-4aa4-a0ce-4fe978abe706/xzy/Downloads/manydepth/manydepth/checkpoint/KITTI_MR",
  "mono_weights_folder": null,
  "models_to_load": [
    "encoder",
    "depth",
    "pose_encoder",
    "pose"
  ],
  "log_frequency": 250,
  "save_frequency": 1,
  "eval_stereo": false,
  "eval_mono": false,
  "disable_median_scaling": false,
  "pred_depth_scale_factor": 1,
  "ext_disp_to_eval": null,
  "eval_split": "eigen",
  "save_pred_disps": false,
  "no_eval": false,
  "eval_eigen_to_benchmark": false,
  "eval_out_dir": null,
  "post_process": false,
  "zero_cost_volume": false,
  "static_camera": false
}

**Comment by mdfirman** [comment]
Hello, and thanks for trying out our repo! It's good to see that you are in fact able to learn some kind of depth map – it looks like you're in the right direction.

It looks from the images that you might perhaps have some problem with intrinsics. Did you update the intrinsics in the dataloader to match the intrinsics for your dataset?

It might be easier to try using the monodepth2 repo first (https://github.com/nianticlabs/monodepth2/) with your data, as monodepth2 is a simpler version of manydepth. This would help you with debugging.  Then once you have good results there you should be able to copy your dataloaders across to manydepth, with minimal changes to make them work here.

I'll leave this issue open for a few more days in case anyone else has any other comments. Thanks

**Comment by xuzhiyuan29** [comment]
Thanks a lot! I found out that I forgot the 25% crop in data preprocessing. I have corrected my intrinsic and dataloader problems and now I have more satisfactory results.
----------------------------------------------------------------------
![微信截图_20210520144555](https://user-images.githubusercontent.com/38434962/118932364-8dbc2b00-b97a-11eb-93a6-dc3d8e1d74b6.png)
----------------------------------------------------------------------

**Comment by mdfirman** [comment]
Great news, these new results look great.

**Comment by ll231** [comment]
hello,what does crop 25% mean？Thank you very much if you answer me

**Comment by ll231** [comment]
> ## Thanks a lot! I found out that I forgot the 25% crop in data preprocessing. I have corrected my intrinsic and dataloader problems and now I have more satisfactory results.
> ## ![微信截图_20210520144555](https://user-images.githubusercontent.com/38434962/118932364-8dbc2b00-b97a-11eb-93a6-dc3d8e1d74b6.png)
hello,what does crop 25% mean？Thank you very much if you answer me
